Hn.standard gauge component
status-im/nimbus-gui pull request #17
Opened 2023-08-07 11:34 UTC by HristoNedelkov

Implement standard gauge using nivo library - (https://nivo.rocks/pie)

On Merge close - #8

2023-08-07 12:05 UTC, RadoslavDimchev commented on src/App.tsx
You can extract StandartGauge in other component

2023-08-07 12:08 UTC, RadoslavDimchev commented on src/App.tsx
> +    <>
You should remove this react fragment

2023-08-07 12:23 UTC, HristoNedelkov commented on src/App.tsx
Yes, thank you.

2023-08-07 12:27 UTC, HristoNedelkov commented on src/App.tsx
> +    <>
Yes, thank you

2023-08-07 12:29 UTC, RadoslavDimchev approved these changes

2023-08-08 07:31 UTC, GoNZooo requested changes
Just some spelling fixes

2023-08-08 07:31 UTC, GoNZooo commented on src/components/StandartGauge.tsx
> +const StandartGauge = ({ data }: StandartGaugeProps) => (
```suggestion
const StandardGauge = ({ data }: StandardGaugeProps) => (
```

2023-08-08 07:31 UTC, GoNZooo commented on src/components/StandartGauge.tsx
> +interface StandartGaugeProps {
```suggestion
interface StandardGaugeProps {
```

2023-08-08 07:31 UTC, GoNZooo commented on src/components/StandartGauge.tsx
> +export default StandartGauge
```suggestion
export default StandardGauge
```

2023-08-08 07:31 UTC, GoNZooo commented on src/App.tsx
> +          <StandartGauge data={data} />
```suggestion
          <StandardGauge data={data} />
```

2023-08-08 07:31 UTC, GoNZooo commented on src/App.tsx
> +import StandartGauge from './components/StandartGauge'
```suggestion
import StandardGauge from './components/StandardGauge'
```

2023-08-08 07:39 UTC, GoNZooo approved these changes
:+1:

2023-08-08 07:42 UTC, merged